source :rubygems
gem "sinatra"
gem "dm-core"
gem "koala"
gem "dm-migrations"
gem "dm-validations"
gem "dm-types"
gem "dm-serializer"
gem "dm-sqlite-adapter"
gem "haml"
gem "sass"
gem "permutation"
gem "extlib"
gem "rake"

gem "mongrel"
gem "thin"
gem "unicorn"
